/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cover.made;

import AppPackage.AnimationClass;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Prakhil
 */
public class disc extends javax.swing.JFrame {

    /**
     * Creates new form disc
     */
    public disc() {
        initComponents();
         AnimationClass a=new AnimationClass();
        a.jLabelXRight(-100, 30, 16, 3, ho);
        a.jLabelXRight(-100, 30, 20, 5, pr);
        a.jLabelXRight(-100, 30, 25, 10, set);
        a.jLabelXRight(-110, 30, 29, 15, ab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ab = new javax.swing.JLabel();
        ho = new javax.swing.JLabel();
        pr = new javax.swing.JLabel();
        set = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover/made/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(983, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel17)
                .addGap(215, 215, 215)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 30, 1250, 120);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover/made/popl.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover/made/output_dYQUAQ.gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("It a medical envelope.more better than other normal envelopes .Its also have ability to take-");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText(" water,because its water resistent and make it also recyclable plastic.Have more durability.");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Its provide more security from bacterias and virus.");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Durability");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Quality");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Water resistent");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Recyclable");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(406, 406, 406))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(200, 150, 1050, 590);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Covermade welcomes you for a good shopping experients.");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1020, 10, 330, 14);

        ab.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        ab.setForeground(new java.awt.Color(255, 255, 255));
        ab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ab.setText("ABOUT US");
        ab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ab.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                abMouseMoved(evt);
            }
        });
        ab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abMouseClicked(evt);
            }
        });
        getContentPane().add(ab);
        ab.setBounds(-110, 360, 140, 30);

        ho.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        ho.setForeground(new java.awt.Color(255, 255, 255));
        ho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ho.setText("HOME");
        ho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hoMouseMoved(evt);
            }
        });
        ho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoMouseClicked(evt);
            }
        });
        getContentPane().add(ho);
        ho.setBounds(-100, 240, 140, 30);

        pr.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        pr.setForeground(new java.awt.Color(255, 255, 255));
        pr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pr.setText("PROFILE");
        pr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                prMouseMoved(evt);
            }
        });
        pr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prMouseClicked(evt);
            }
        });
        getContentPane().add(pr);
        pr.setBounds(-100, 280, 140, 30);

        set.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        set.setForeground(new java.awt.Color(255, 255, 255));
        set.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set.setText("SETTINGS");
        set.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        set.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                setMouseMoved(evt);
            }
        });
        set.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setMouseClicked(evt);
            }
        });
        getContentPane().add(set);
        set.setBounds(-100, 320, 140, 30);

        jLabel13.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover/made/wf.jpg"))); // NOI18N
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel13MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, -6, 1360, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseMoved
        ho.setForeground(new java.awt.Color(255, 255, 255));
        ab.setForeground(new java.awt.Color(255, 255, 255));
        pr.setForeground(new java.awt.Color(255, 255, 255));
        set.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel13MouseMoved

    private void abMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseMoved
        ab.setForeground(new java.awt.Color(0, 155, 255));
    }//GEN-LAST:event_abMouseMoved

    private void hoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoMouseMoved
        ho.setForeground(new java.awt.Color(0, 155, 255));
    }//GEN-LAST:event_hoMouseMoved

    private void prMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prMouseMoved
        pr.setForeground(new java.awt.Color(0, 155, 255));
    }//GEN-LAST:event_prMouseMoved

    private void setMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMouseMoved
        set.setForeground(new java.awt.Color(0, 155, 255));
    }//GEN-LAST:event_setMouseMoved

    private void hoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoMouseClicked
    
        home h=new home();
       h.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_hoMouseClicked

    private void prMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prMouseClicked
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement)con.createStatement();
            String sql12="update reminder set profilep=1 where id=1;";
                        PreparedStatement ps12=con.prepareStatement(sql12);
                        ps12.execute();
           
       home h=new home();
       h.setVisible(true);
       this.setVisible(false);
       }
       catch(ClassNotFoundException | SQLException e){}
       
    }//GEN-LAST:event_prMouseClicked

    private void setMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMouseClicked
       try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement)con.createStatement();
            String sql12="update reminder set settings1=1 where id=1;";
                        PreparedStatement ps12=con.prepareStatement(sql12);
                        ps12.execute();
        home h=new home();
       h.setVisible(true);
       this.setVisible(false);
    }catch(ClassNotFoundException | SQLException e){}
    }//GEN-LAST:event_setMouseClicked

    private void abMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseClicked
        try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement)con.createStatement();
            String sql12="update reminder set settings1=1 where id=1;";
                        PreparedStatement ps12=con.prepareStatement(sql12);
                        ps12.execute();
        home h=new home();
       h.setVisible(true);
       this.setVisible(false);
    }catch(ClassNotFoundException | SQLException e){}
    }//GEN-LAST:event_abMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(disc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(disc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(disc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(disc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new disc().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ab;
    private javax.swing.JLabel ho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pr;
    private javax.swing.JLabel set;
    // End of variables declaration//GEN-END:variables
}
