/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cover.made;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Prakhil
 */
public class login extends javax.swing.JFrame {
    Connection con=null;
    public login() {
        
        initComponents();
    try{
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
                try{
                Class.forName("com.mysql.jdbc.driver");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement)con.createStatement();
                String sql2="select * from reminder ";
                PreparedStatement pst2 = con.prepareStatement(sql2);
                ResultSet rs =pst2.executeQuery();
                if(rs.next())
                {
                  String user=(String)rs.getObject(1);
                  String pass=(String)rs.getObject(2);
                  String ab=rs.getString("selection");
                  int a=Integer.parseInt(ab);
                  if(a==1)
                  {
                      txt7.setText(""+user);
                      txt8.setText(""+pass);
                  
                  
                  }
                  
                }
                
                }
                catch(SQLException | NumberFormatException e)
                {
                    
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt8 = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        checker = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        day = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        txt3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt4 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        district = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        ad1 = new javax.swing.JTextField();
        test = new javax.swing.JTextField();
        ad2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(327670, 327670));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("CoVEr");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 680, 30));

        jLabel15.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 51));
        jLabel15.setText(" MaDE");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 4, 690, 30));

        jLabel6.setBackground(new java.awt.Color(51, 153, 255));
        jLabel6.setFont(new java.awt.Font("Rod", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Belief.That's Everything");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 1360, 16));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(204, 0, 255));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 51));
        jLabel16.setText("Username  :");

        txt7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, new java.awt.Color(102, 102, 102), java.awt.Color.darkGray));
        txt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt7MouseClicked(evt);
            }
        });
        txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt7ActionPerformed(evt);
            }
        });
        txt7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt7KeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 51));
        jLabel17.setText("Password  :");

        txt8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, new java.awt.Color(102, 102, 102), java.awt.Color.darkGray));
        txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8ActionPerformed(evt);
            }
        });
        txt8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt8KeyPressed(evt);
            }
        });

        login.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        login.setForeground(new java.awt.Color(204, 0, 51));
        login.setText("Log In");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("remember me");

        checker.setBackground(new java.awt.Color(51, 51, 51));
        checker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(771, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checker)
                        .addGap(314, 314, 314)))
                .addComponent(login)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checker, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel17)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1370, 78));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Sign Up");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 150, 108, 39));

        txt1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(153, 153, 153));
        txt1.setText("first name");
        txt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, new java.awt.Color(51, 51, 51), java.awt.Color.gray));
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
        });
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
        });
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 207, 186, -1));

        txt2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        txt2.setForeground(new java.awt.Color(153, 153, 153));
        txt2.setText("Last name");
        txt2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, new java.awt.Color(51, 51, 51), java.awt.Color.darkGray));
        txt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt2MouseClicked(evt);
            }
        });
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 207, 191, -1));

        jLabel21.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Birth Day     :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 23));

        year.setEditable(true);
        year.setMaximumRowCount(12);
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 65, 24));

        month.setEditable(true);
        month.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        month.setMaximumRowCount(13);
        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec" }));
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 71, 24));

        day.setEditable(true);
        day.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        day.setMaximumRowCount(32);
        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.setAutoscrolls(true);
        jPanel1.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 57, 25));

        jLabel22.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("Sex           :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 90, 33));

        male.setBackground(new java.awt.Color(0, 0, 0));
        male.setForeground(new java.awt.Color(153, 153, 153));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 60, -1));

        female.setBackground(new java.awt.Color(0, 0, 0));
        female.setForeground(new java.awt.Color(153, 153, 153));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 70, -1));

        txt3.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        txt3.setForeground(new java.awt.Color(153, 153, 153));
        txt3.setText("E-mail  address");
        txt3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        txt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt3MouseClicked(evt);
            }
        });
        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt3KeyPressed(evt);
            }
        });
        jPanel1.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 395, 32));

        txt4.setColumns(10);
        txt4.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        txt4.setForeground(new java.awt.Color(153, 153, 153));
        txt4.setRows(5);
        txt4.setText("address");
        txt4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.lightGray));
        txt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt4MouseClicked(evt);
            }
        });
        txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt4KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txt4);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 395, 80));

        jLabel23.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Phone no     :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 100, -1));

        txt5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt5.setForeground(new java.awt.Color(51, 51, 51));
        txt5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, new java.awt.Color(51, 51, 51), java.awt.Color.darkGray));
        txt5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt5KeyPressed(evt);
            }
        });
        jPanel1.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 291, 29));

        jLabel24.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Pin code      :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 100, 25));

        txt6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt6.setForeground(new java.awt.Color(51, 51, 51));
        txt6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        txt6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });
        jPanel1.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 291, 30));

        district.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        district.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select District- ", "Thiruvanathapuram", "Kollam", "Pathanamthitta", "Kottayam", "Alapuzha", "Idukki", "Eranakulam", "Thrissur", "Palakkad", "Malappuram", "Calicut", "Kannur", "Vayanadu", "Kaserkode" }));
        district.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtActionPerformed(evt);
            }
        });
        jPanel1.add(district, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 210, 30));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover/made/banner_publications1.jpg"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 214, 660, 370));

        signin.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        signin.setForeground(new java.awt.Color(204, 0, 51));
        signin.setText("Sign In");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        jPanel1.add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 650, 90, 40));

        jLabel26.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover/made/wf.jpg"))); // NOI18N
        jLabel26.setText("nhfcvbbv");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1360, 750));

        ad1.setText("prakhil");
        jPanel1.add(ad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));
        jPanel1.add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        ad2.setText("123");
        jPanel1.add(ad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
      public void run()
  {
      if(checker.isSelected()==true){
          
              String a =txt7.getText();
              String b=txt8.getText();
         try {
              
              String sql="update reminder set username=? where id=1;";
              PreparedStatement pst = con.prepareStatement(sql);
              pst.setString(1, a);
              pst.execute();
              String sql1="update reminder set password=? where id=1;";
              PreparedStatement pst1 = con.prepareStatement(sql1);
              pst1.setString(1, b);
              pst1.execute();
              String sql2="update reminder set selection=1 where id=1; ";
              PreparedStatement pst2 = con.prepareStatement(sql2);
              pst2.execute();
              }catch(SQLException e){}
      }
      else if(checker.isSelected()==false)
      {     try{
                
                String sql2="update reminder set selection=0 where id=1; ";
                PreparedStatement pst2 = con.prepareStatement(sql2);
                pst2.execute();
                
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
      
      }
  }
//</editor-fold>
 public String m;
 public static String username;                                       
    private void txt7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt7MouseClicked
        String a,b;
        a=txt1.getText();
        b=test.getText();
        if(a.equals(b))
        {
            txt1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt1.setForeground(new java.awt.Color(153, 153, 153));
            txt1.setText("first name");
        }
        a=txt2.getText();
        if(a.equals(b))
        {
            txt2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt2.setForeground(new java.awt.Color(153, 153, 153));
            txt2.setText("Last name");
        }
        a=txt3.getText();
        if(a.equals(b))
        {
            txt3.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt3.setForeground(new java.awt.Color(153, 153, 153));
            txt3.setText("E-mail  address");
        }
        a=txt4.getText();
        if(a.equals(b))
        {
            txt4.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt4.setForeground(new java.awt.Color(153, 153, 153));
            txt4.setText("address");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_txt7MouseClicked

    private void txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt7ActionPerformed

    private void txt7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt7KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){txt8.requestFocusInWindow();}
    }//GEN-LAST:event_txt7KeyPressed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       if(txt7.getText().equals(ad1.getText())&&txt8.getText().equals(ad2.getText()))
        {
            
            admin ad=new admin();
            ad.setVisible(true);
            this.setVisible(false);
            
            
        }
        else{
            try {

                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
                try {
                    Class.forName("com.mysql.jdbc.driver");
                }
                catch (ClassNotFoundException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                String sql = "select * from login where username=? and password=?";

                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1,txt7.getText());
                pst.setString(2, txt8.getText());
                ResultSet rs = pst.executeQuery();
                if(rs.next())
                {
                    username=txt7.getText();
                    run();

                    //  QueryJFrame s = new QueryJFrame();
                    home h1=new home();
                    h1.setVisible(true);
                    this.hide();
                } else
                {
                    JOptionPane.showMessageDialog(null, "Incorrect username or password");

                }
                
            }
            catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
        String a,b;
        a=txt2.getText();
        b=test.getText();
        if(a.equals(b)){
            txt2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt2.setForeground(new java.awt.Color(153, 153, 153));
            txt2.setText("Last name");
        }
        a=txt3.getText();
        if(a.equals(b))
        {
            txt3.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt3.setForeground(new java.awt.Color(153, 153, 153));
            txt3.setText("E-mail  address");
        }
        a=txt4.getText();
        if(a.equals(b)){
            txt4.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt4.setForeground(new java.awt.Color(153, 153, 153));
            txt4.setText("address");
        }
        if("first name".equals(txt1.getText())){
        txt1.setText(null);
        txt1.setFont(new java.awt.Font("Times New Roman", 0, 18));
        txt1.setForeground(new java.awt.Color(51, 51, 51));}// TODO add your handling code here:
    }//GEN-LAST:event_txt1MouseClicked

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt2MouseClicked
        String a,b;
        a=txt1.getText();
        b=test.getText();
        if(a.equals(b))
        {
            txt1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt1.setForeground(new java.awt.Color(153, 153, 153));
            txt1.setText("first name");
        }
        a=txt3.getText();
        if(a.equals(b))
        {
            txt3.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt3.setForeground(new java.awt.Color(153, 153, 153));
            txt3.setText("E-mail  address");
        }
        a=txt4.getText();
        if(a.equals(b)){
            txt4.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt4.setForeground(new java.awt.Color(153, 153, 153));
            txt4.setText("address");
        }
        if("Last name".equals(txt2.getText())){
        txt2.setText(null);
        txt2.setFont(new java.awt.Font("Times New Roman", 0, 18));
        txt2.setForeground(new java.awt.Color(51, 51, 51)); }   // TODO add your handling code here:
    }//GEN-LAST:event_txt2MouseClicked

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        if(male.isSelected()==true)
        { m="Male";
            female.setSelected(false);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        if(female.isSelected()==true)
        {
            m="Female";
            male.setSelected(false);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void txt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt3MouseClicked
        String a,b;
        a=txt1.getText();
        b=test.getText();
        if(a.equals(b))
        {
            txt1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt1.setForeground(new java.awt.Color(153, 153, 153));
            txt1.setText("first name");
        }
        a=txt2.getText();
        if(a.equals(b))
        {
            txt2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt2.setForeground(new java.awt.Color(153, 153, 153));
            txt2.setText("Last name");
        }
        a=txt4.getText();
        if(a.equals(b)){
            txt4.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt4.setForeground(new java.awt.Color(153, 153, 153));
            txt4.setText("address");
        }
        if("E-mail  address".equals(txt3.getText())){
        txt3.setText(null);
        txt3.setFont(new java.awt.Font("Times New Roman", 0, 18));
        txt3.setForeground(new java.awt.Color(51, 51, 51));}    // TODO add your handling code here:
    }//GEN-LAST:event_txt3MouseClicked

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt4MouseClicked
        String a,b;
        a=txt1.getText();
        b=test.getText();
        if(a.equals(b))
        {
            txt1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt1.setForeground(new java.awt.Color(153, 153, 153));
            txt1.setText("first name");
        }
        a=txt2.getText();
        if(a.equals(b))
        {
            txt2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt2.setForeground(new java.awt.Color(153, 153, 153));
            txt2.setText("Last name");
        }
        a=txt3.getText();
        if(a.equals(b))
        {
            txt3.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt3.setForeground(new java.awt.Color(153, 153, 153));
            txt3.setText("E-mail  address");
        }
        if("address".equals(txt4.getText())){
        txt4.setText(null);
        txt4.setFont(new java.awt.Font("Times New Roman", 0, 18));
        txt4.setForeground(new java.awt.Color(51, 51, 51)); }  // TODO add your handling code here:
    }//GEN-LAST:event_txt4MouseClicked

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6ActionPerformed

    private void districtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        try {
            username=txt1.getText();
            String a =(String) day.getSelectedItem();
            String b =(String) month.getSelectedItem();
            String c =(String) year.getSelectedItem();
            String d =a+"/"+b+"/"+c;

            String sql="insert into signin(firstname,lastname,birthday,sex,emailaddress,address,phone,pincode,district,id)values(?,?,?,?,?,?,?,?,?,?)";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement)con.createStatement();
            String query="select id from signin order by id desc limit 1";
        PreparedStatement ps=con.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            int id;
            String ids="";
            
            if(rs.next())
            {
                 id=(int) rs.getObject(1);
                id=id+1;
                ids=String.valueOf(id);
                
            }
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, txt1.getText());
            pst.setString(2, txt2.getText());
            pst.setString(3,d);
            pst.setString(4,m);
            pst.setString(5, txt3.getText());
            pst.setString(6, txt4.getText());
            pst.setString(7,txt5.getText() );
            pst.setString(8,txt6.getText());
            pst.setString(9,(String)district.getSelectedItem());
            pst.setString(10,ids);
            pst.execute();
            

            user o=new user();
            o.setVisible(true);
            this.hide();

        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }// TODO add your handling code here:
    }//GEN-LAST:event_signinActionPerformed

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        String a,b;
        a=txt1.getText();
        b=test.getText();
        if(a.equals(b))
        {
            txt1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt1.setForeground(new java.awt.Color(153, 153, 153));
            txt1.setText("first name");
        }
        a=txt2.getText();
        if(a.equals(b))
        {
            txt2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt2.setForeground(new java.awt.Color(153, 153, 153));
            txt2.setText("Last name");
        }
        a=txt3.getText();
        if(a.equals(b))
        {
            txt3.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt3.setForeground(new java.awt.Color(153, 153, 153));
            txt3.setText("E-mail  address");
        }
        a=txt4.getText();
        if(a.equals(b)){
            txt4.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
            txt4.setForeground(new java.awt.Color(153, 153, 153));
            txt4.setText("address");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void checkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkerActionPerformed

    }//GEN-LAST:event_checkerActionPerformed

    private void txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8ActionPerformed
      
    }//GEN-LAST:event_txt8ActionPerformed

    private void txt8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt8KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                 if(txt7.getText().equals(ad1.getText())&&txt8.getText().equals(ad2.getText()))
        {
            
            admin ad=new admin();
            ad.setVisible(true);
            this.setVisible(false);
            
            
        }
        else{
            try {

                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
                try {
                    Class.forName("com.mysql.jdbc.driver");
                }
                catch (ClassNotFoundException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                String sql = "select * from login where username=? and password=?";

                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1,txt7.getText());
                pst.setString(2, txt8.getText());
                ResultSet rs = pst.executeQuery();
                if(rs.next())
                {
                    username=txt7.getText();
                    run();

                    //  QueryJFrame s = new QueryJFrame();
                    home h1=new home();
                    h1.setVisible(true);
                    this.hide();
                } else
                {
                    JOptionPane.showMessageDialog(null, "Incorrect username or password");

                }
                
            }
            catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
            }
    }//GEN-LAST:event_txt8KeyPressed

    private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        txt2.requestFocusInWindow();
        txt2.setText(null);
        txt2.setFont(new java.awt.Font("Times New Roman", 0, 18));
        txt2.setForeground(new java.awt.Color(51, 51, 51));
       
       }
        
    }//GEN-LAST:event_txt1KeyPressed

    private void txt3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt3KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           txt4.setText(null);
        txt4.setFont(new java.awt.Font("Times New Roman", 0, 18));
        txt4.setForeground(new java.awt.Color(51, 51, 51));
        txt4.requestFocusInWindow();
       
       }
    }//GEN-LAST:event_txt3KeyPressed

    private void txt4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt4KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){txt5.requestFocusInWindow();}
    }//GEN-LAST:event_txt4KeyPressed

    private void txt5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){txt6.requestFocusInWindow();}
    }//GEN-LAST:event_txt5KeyPressed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad1;
    private javax.swing.JPasswordField ad2;
    private javax.swing.JCheckBox checker;
    private javax.swing.JComboBox day;
    private javax.swing.JComboBox district;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton login;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox month;
    private javax.swing.JButton signin;
    private javax.swing.JTextField test;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextArea txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JPasswordField txt8;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
