/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cover.made;

import AppPackage.AnimationClass;
import static cover.made.login.username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Prakhil
 */
public class Thanks extends javax.swing.JFrame {

    /**
     * Creates new form Thanks
     */
    public Thanks() {
        initComponents();
        
        AnimationClass a=new AnimationClass();
        a.jLabelXRight(-60, 30, 55, 4, ho);
        a.jLabelXRight(-80, 20, 60, 5, pr);
        a.jLabelXRight(-80, 25, 65, 7, set);
        a.jLabelXRight(-80, 25, 69, 10, ab);
        try {
                
               String sql = "select * from signin where firstname=?";
              try {
                  Class.forName("com.mysql.jdbc.driver");
              } catch (ClassNotFoundException ex) {
                  Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
              }
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");  
            com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement)con.createStatement();
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,username);
            
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                   th1.setText((String) rs.getObject(1)+" "+(String) rs.getObject(2));
                   th2.setText((String) rs.getObject(6));
                   th3.setText((String) rs.getObject(9)+","+(String) rs.getObject(8));
                   th4.setText("Ph :"+(String) rs.getObject(7));
                  
            }
               
         } catch (SQLException ex) {
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        soon = new javax.swing.JLabel();
        th1 = new javax.swing.JLabel();
        th2 = new javax.swing.JLabel();
        th3 = new javax.swing.JLabel();
        th4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ho = new javax.swing.JLabel();
        pr = new javax.swing.JLabel();
        set = new javax.swing.JLabel();
        ab = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover/made/il_570xN.412705039_dgx9.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Thank you  for shopping. ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        soon.setFont(new java.awt.Font("Most Wazted", 1, 36)); // NOI18N
        soon.setForeground(new java.awt.Color(102, 102, 102));
        soon.setText("You will get it soon");

        th1.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        th1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        th1.setText("Prakhil");

        th2.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        th2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        th2.setText("Prakhil");

        th3.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        th3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        th3.setText("Prakhil");

        th4.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        th4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        th4.setText("Prakhil");

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        jLabel3.setText("Available address  :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(th2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(th1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(th3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(th4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(soon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(th1)
                        .addGap(4, 4, 4)
                        .addComponent(th2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(th3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(th4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(soon)
                .addGap(59, 59, 59))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 130, 1190, 590);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CoVEr");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 30, 160, 30);

        jLabel14.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 51));
        jLabel14.setText(" MaDE");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(290, 30, 170, 30);

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Belief.That's Everything....");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 80, 270, 16);

        ho.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        ho.setForeground(new java.awt.Color(255, 255, 255));
        ho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ho.setText("HOME");
        ho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hoMouseMoved(evt);
            }
        });
        ho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoMouseClicked(evt);
            }
        });
        getContentPane().add(ho);
        ho.setBounds(-60, 320, 80, 30);

        pr.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        pr.setForeground(new java.awt.Color(255, 255, 255));
        pr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pr.setText("PROFILE");
        pr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                prMouseMoved(evt);
            }
        });
        pr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prMouseClicked(evt);
            }
        });
        getContentPane().add(pr);
        pr.setBounds(-80, 360, 100, 30);

        set.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        set.setForeground(new java.awt.Color(255, 255, 255));
        set.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set.setText("SETTINGS");
        set.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        set.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                setMouseMoved(evt);
            }
        });
        set.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setMouseClicked(evt);
            }
        });
        getContentPane().add(set);
        set.setBounds(-80, 400, 90, 30);

        ab.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        ab.setForeground(new java.awt.Color(255, 255, 255));
        ab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ab.setText("ABOUT US");
        ab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ab.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                abMouseMoved(evt);
            }
        });
        ab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abMouseClicked(evt);
            }
        });
        getContentPane().add(ab);
        ab.setBounds(-80, 440, 90, 30);

        jLabel13.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover/made/wf.jpg"))); // NOI18N
        jLabel13.setText("Sign in");
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel13MouseMoved(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, -6, 1360, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseMoved
      ho.setForeground(new java.awt.Color(255, 255, 255));
        ab.setForeground(new java.awt.Color(255, 255, 255));
        pr.setForeground(new java.awt.Color(255, 255, 255));
        set.setForeground(new java.awt.Color(255, 255, 255));  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void hoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoMouseMoved
        ho.setForeground(new java.awt.Color(0, 155, 255));
    }//GEN-LAST:event_hoMouseMoved

    private void hoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoMouseClicked

        home h=new home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hoMouseClicked

    private void prMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prMouseMoved
        pr.setForeground(new java.awt.Color(0, 155, 255));
    }//GEN-LAST:event_prMouseMoved

    private void prMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prMouseClicked
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement)con.createStatement();
            String sql12="update reminder set profilep=1 where id=1;";
            PreparedStatement ps12=con.prepareStatement(sql12);
            ps12.execute();

            home h=new home();
            h.setVisible(true);
            this.setVisible(false);
        }
        catch(ClassNotFoundException | SQLException e){}

    }//GEN-LAST:event_prMouseClicked

    private void setMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMouseMoved
        set.setForeground(new java.awt.Color(0, 155, 255));
    }//GEN-LAST:event_setMouseMoved

    private void setMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMouseClicked
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement)con.createStatement();
            String sql12="update reminder set settings1=1 where id=1;";
            PreparedStatement ps12=con.prepareStatement(sql12);
            ps12.execute();
            home h=new home();
            h.setVisible(true);
            this.setVisible(false);
        }catch(ClassNotFoundException | SQLException e){}
    }//GEN-LAST:event_setMouseClicked

    private void abMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseMoved
        ab.setForeground(new java.awt.Color(0, 155, 255));
    }//GEN-LAST:event_abMouseMoved

    private void abMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseClicked
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "");
            com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement)con.createStatement();
            String sql12="update reminder set settings1=1 where id=1;";
            PreparedStatement ps12=con.prepareStatement(sql12);
            ps12.execute();
            home h=new home();
            h.setVisible(true);
            this.setVisible(false);
        }catch(ClassNotFoundException | SQLException e){}
    }//GEN-LAST:event_abMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Thanks().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ab;
    private javax.swing.JLabel ho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pr;
    private javax.swing.JLabel set;
    private javax.swing.JLabel soon;
    private javax.swing.JLabel th1;
    private javax.swing.JLabel th2;
    private javax.swing.JLabel th3;
    private javax.swing.JLabel th4;
    // End of variables declaration//GEN-END:variables
}
